2018-01-24 23:44:34.273507: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:44:34 tf_logging:82] Restoring parameters from ./model/demo
<class 'bytes'>
> Building prefix dict from the default dictionary ...
[D 180124 23:44:34 __init__:111] Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
[D 180124 23:44:34 __init__:131] Loading model from cache /tmp/jieba.cache
Loading model cost 0.927 seconds.
[D 180124 23:44:35 __init__:163] Loading model cost 0.927 seconds.
Prefix dict has been built succesfully.
[D 180124 23:44:35 __init__:164] Prefix dict has been built succesfully.
[I 180124 23:44:35 web:2063] 200 GET /?input=good (192.168.3.6) 1360.99ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:44:42 tf_logging:82] Restoring parameters from ./model/demo
Sorry like to with Please with Please with Please with
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:44:42 web:2063] 200 GET /?input=how%20are%20you (192.168.3.6) 409.06ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:44:48 tf_logging:82] Restoring parameters from ./model/demo
Good
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:44:48 web:2063] 200 GET /?input=hello (192.168.3.6) 351.83ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:44:57 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:44:57 web:2063] 200 GET /?input=do%20you%20have%20name (192.168.3.6) 414.06ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:45:06 tf_logging:82] Restoring parameters from ./model/demo
How do you do
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:45:06 web:2063] 200 GET /?input=what%20is%20your%20name (192.168.3.6) 435.04ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:45:13 tf_logging:82] Restoring parameters from ./model/demo
This to to help
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:45:13 web:2063] 200 GET /?input=good%20night (192.168.3.6) 410.20ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:45:21 tf_logging:82] Restoring parameters from ./model/demo
Sorry like to with Please with Please with Please with
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:45:22 web:2063] 200 GET /?input=Good%20night (192.168.3.6) 415.64ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:45:28 tf_logging:82] Restoring parameters from ./model/demo
Thank you The same to you
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:45:29 web:2063] 200 GET /?input=Good%20morning (192.168.3.6) 404.41ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:45:56 tf_logging:82] Restoring parameters from ./model/demo
Good morning
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:45:56 web:2063] 200 GET /?input=hd (192.168.3.6) 316.54ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:45:58 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:45:59 web:2063] 200 GET /?input=ll (192.168.3.6) 320.93ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:01 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:46:01 web:2063] 304 GET /?input=ll (192.168.3.6) 334.76ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:06 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:46:06 web:2063] 304 GET /?input=how%20are%20you (192.168.3.6) 425.26ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:10 tf_logging:82] Restoring parameters from ./model/demo
Good
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:46:11 web:2063] 200 GET /?input=good (192.168.3.6) 396.60ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:15 tf_logging:82] Restoring parameters from ./model/demo
Sorry like to with Please with Please with Please with
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:46:15 web:2063] 200 GET /?input=go%20home (192.168.3.6) 326.99ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:21 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:46:22 web:2063] 200 GET /?input=where%20are%20you (192.168.3.6) 416.19ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:29 tf_logging:82] Restoring parameters from ./model/demo
Good
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:46:29 web:2063] 200 GET /?input=have%20a%20rest (192.168.3.6) 413.51ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:39 tf_logging:82] Restoring parameters from ./model/demo
Thank you Have a nice
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:46:39 web:2063] 200 GET /?input=has%20a%20rest (192.168.3.6) 424.33ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:45 tf_logging:82] Restoring parameters from ./model/demo
How afternoon
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:46:45 web:2063] 200 GET /?input=have%20rest (192.168.3.6) 318.62ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:54 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:46:55 web:2063] 200 GET /?input=name (192.168.3.6) 314.66ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:46:59 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:47:00 web:2063] 200 GET /?input=bad (192.168.3.6) 313.45ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:47:05 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:47:05 web:2063] 200 GET /?input=not%20good (192.168.3.6) 405.67ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:55:40 tf_logging:82] Restoring parameters from ./model/demo
I like much with Please with Please with Please with
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:55:40 web:2063] 200 GET /?input=hi (192.168.3.6) 311.16ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:55:47 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:55:47 web:2063] 304 GET /?input=how%20are%20you (192.168.3.6) 429.53ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:55:55 tf_logging:82] Restoring parameters from ./model/demo
Good
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:55:55 web:2063] 200 GET /?input=how%20do%20you%20do (192.168.3.6) 414.94ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:56:17 tf_logging:82] Restoring parameters from ./model/demo
How afternoon
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:56:17 web:2063] 200 GET /?input=how%20are%20yo (192.168.3.6) 425.25ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:56:24 tf_logging:82] Restoring parameters from ./model/demo
Thank you
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:56:24 web:2063] 304 GET /?input=hi (192.168.3.6) 318.67ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:56:28 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:56:28 web:2063] 304 GET /?input=hello (192.168.3.6) 310.36ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:56:34 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:56:35 web:2063] 200 GET /?input=good%20name (192.168.3.6) 408.18ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:57:58 tf_logging:82] Restoring parameters from ./model/demo
Sorry like to with Please with Please with Please with
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:57:59 web:2063] 200 GET /?input=hi,all (192.168.3.6) 324.94ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:58:12 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180124 23:58:12 web:2063] 200 GET /?input=hello%20,%20your%20name (192.168.3.6) 409.48ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:58:22 tf_logging:82] Restoring parameters from ./model/demo
Sorry you with with you with Please with Please with
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:58:22 web:2063] 304 GET /?input=where%20are%20you (192.168.3.6) 417.83ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180124 23:58:29 tf_logging:82] Restoring parameters from ./model/demo
Good
<class 'bytes'>
<class 'bytes'>
> [I 180124 23:58:29 web:2063] 200 GET /?input=bad%20name (192.168.3.6) 315.42ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180125 00:00:18 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180125 00:00:18 web:2063] 304 GET /?input=hello (192.168.3.6) 307.86ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180125 00:00:24 tf_logging:82] Restoring parameters from ./model/demo
WARN：词汇不在服务区
<class 'str'>
<class 'bytes'>
> [I 180125 00:00:24 web:2063] 200 GET /?input=good%20morning (192.168.3.6) 421.22ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180125 00:00:30 tf_logging:82] Restoring parameters from ./model/demo
Good evening
<class 'bytes'>
<class 'bytes'>
> [I 180125 00:00:30 web:2063] 304 GET /?input=good%20night (192.168.3.6) 417.93ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180125 00:02:25 tf_logging:82] Restoring parameters from ./model/demo
Sorry like to with Please with Please with Please with
<class 'bytes'>
<class 'bytes'>
> [I 180125 00:02:26 web:2063] 200 GET /?input=where%20are%20you%20going (192.168.3.6) 405.38ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180125 00:19:27 tf_logging:82] Restoring parameters from ./model/demo
How you
<class 'bytes'>
<class 'bytes'>
> [I 180125 00:19:28 web:2063] 200 GET /?input=how%20are%20you (192.168.3.6) 435.87ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180207 21:24:13 tf_logging:82] Restoring parameters from ./model/demo
[E 180207 21:24:13 web:1590] Uncaught exception GET /?input=hello (192.168.3.6)
    HTTPServerRequest(protocol='http', host='server_seq2seqEn', method='GET', uri='/?input=hello', version='HTTP/1.0', remote_ip='192.168.3.6', headers={'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://awareness.lenovo.com/smallwebsmallEnglish/smallTalk.html', 'Cookie': '_ga=GA1.2.673393067.1497174576; s_fid=3EB334A903BFC9EE-07AB969EF54F6749; s_vi=[CS]v1|2C7F8275052A1688-40000111200103C2[CE]', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'Host': 'server_seq2seqEn', 'X-Requested-With': 'XMLHttpRequest', 'Accept': '*/*', 'Connection': 'close', 'If-None-Match': '"2be88ca4242c76e8253ac62474851065032d6833"', 'Accept-Language': 'zh-CN,zh;q=0.9'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
        return fn(*args)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
        status, run_metadata)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
        c_api.TF_GetCode(self.status.status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [129] rhs shape= [1216]
    	 [[Node: save/Assign_11 = Assign[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/bias, save/RestoreV2_11)]]
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado-4.5.2-py3.5-linux-x86_64.egg/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "http_english_chat.py", line 290, in get
        respon = generateSentence(word1)
      File "http_english_chat.py", line 245, in generateSentence
        saver.restore(sess, './model/demo')
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
        {self.saver_def.filename_tensor_name: save_path})
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
        run_metadata_ptr)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
        feed_dict_tensor, options, run_metadata)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
        options, run_metadata)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [129] rhs shape= [1216]
    	 [[Node: save/Assign_11 = Assign[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/bias, save/RestoreV2_11)]]
    
    Caused by op 'save/Assign_11', defined at:
      File "http_english_chat.py", line 241, in <module>
        encoder_inputs, decoder_inputs, target_weights, outputs, loss, update, saver, learning_rate_decay_op, learning_rate = get_model(feed_previous=True)
      File "http_english_chat.py", line 164, in get_model
        saver = tf.train.Saver(tf.global_variables())
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
        self.build()
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
        self._build(self._filename, build_save=True, build_restore=True)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
        build_save=build_save, build_restore=build_restore)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
        restore_sequentially, reshape)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 439, in _AddRestoreOps
        assign_ops.append(saveable.restore(tensors, shapes))
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 160, in restore
        self.op.get_shape().is_fully_defined())
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
        validate_shape=validate_shape)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
        use_locking=use_locking, name=name)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
        op_def=op_def)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
    
    InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [129] rhs shape= [1216]
    	 [[Node: save/Assign_11 = Assign[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/bias, save/RestoreV2_11)]]
    
[E 180207 21:24:14 web:2063] 500 GET /?input=hello (192.168.3.6) 232.73ms
INFO:tensorflow:Restoring parameters from ./model/demo
[I 180207 21:24:24 tf_logging:82] Restoring parameters from ./model/demo
[E 180207 21:24:24 web:1590] Uncaught exception GET /?input=hello (192.168.3.6)
    HTTPServerRequest(protocol='http', host='server_seq2seqEn', method='GET', uri='/?input=hello', version='HTTP/1.0', remote_ip='192.168.3.6', headers={'Accept-Encoding': 'gzip, deflate, br', 'Referer': 'https://awareness.lenovo.com/smallwebsmallEnglish/smallTalk.html', 'Cookie': '_ga=GA1.2.673393067.1497174576; s_fid=3EB334A903BFC9EE-07AB969EF54F6749; s_vi=[CS]v1|2C7F8275052A1688-40000111200103C2[CE]', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'Host': 'server_seq2seqEn', 'X-Requested-With': 'XMLHttpRequest', 'Accept': '*/*', 'Connection': 'close', 'Accept-Language': 'zh-CN,zh;q=0.9'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
        return fn(*args)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
        status, run_metadata)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
        c_api.TF_GetCode(self.status.status))
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [8,129] rhs shape= [8,1216]
    	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/kernel, save/RestoreV2_12)]]
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado-4.5.2-py3.5-linux-x86_64.egg/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "http_english_chat.py", line 290, in get
        respon = generateSentence(word1)
      File "http_english_chat.py", line 245, in generateSentence
        saver.restore(sess, './model/demo')
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
        {self.saver_def.filename_tensor_name: save_path})
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
        run_metadata_ptr)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
        feed_dict_tensor, options, run_metadata)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
        options, run_metadata)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [8,129] rhs shape= [8,1216]
    	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/kernel, save/RestoreV2_12)]]
    
    Caused by op 'save/Assign_12', defined at:
      File "http_english_chat.py", line 241, in <module>
        encoder_inputs, decoder_inputs, target_weights, outputs, loss, update, saver, learning_rate_decay_op, learning_rate = get_model(feed_previous=True)
      File "http_english_chat.py", line 164, in get_model
        saver = tf.train.Saver(tf.global_variables())
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
        self.build()
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
        self._build(self._filename, build_save=True, build_restore=True)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
        build_save=build_save, build_restore=build_restore)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
        restore_sequentially, reshape)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 439, in _AddRestoreOps
        assign_ops.append(saveable.restore(tensors, shapes))
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 160, in restore
        self.op.get_shape().is_fully_defined())
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
        validate_shape=validate_shape)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
        use_locking=use_locking, name=name)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
        op_def=op_def)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
        op_def=op_def)
      File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
        self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
    
    InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [8,129] rhs shape= [8,1216]
    	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_attention_seq2seq/embedding_attention_decoder/attention_decoder/output_projection_wrapper/kernel, save/RestoreV2_12)]]
    
[E 180207 21:24:24 web:2063] 500 GET /?input=hello (192.168.3.6) 240.50ms
